{% set version = '1.3' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-estimability
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/estimability_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/estimability/estimability_{{ version }}.tar.gz
  sha256: a33179c5fbd6a1a623d90cb6f1743148f92c09429fac466867f3ea70946a2e32

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]

  host:
    - r-base

  run:
    - r-base

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('estimability')"           # [not win]
    - "\"%R%\" -e \"library('estimability')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=estimability
  license: GPL (>= 3)
  summary: Provides tools for determining estimability of linear functions  of regression coefficients,
    and 'epredict' methods that handle  non-estimable cases correctly. Estimability
    theory is discussed in many linear-models textbooks including Chapter 3 of Monahan,
    JF (2008),  "A Primer on Linear Models", Chapman and Hall (ISBN 978-1-4200-6201-4).
  license_family: GPL3

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: estimability
# Type: Package
# Title: Tools for Assessing Estimability of Linear Predictions
# Version: 1.3
# Date: 2018-02-10
# Authors@R: c(person("Russell", "Lenth", role = c("aut", "cre", "cph"),  email = "russell-lenth@uiowa.edu"))
# Depends: stats
# Description: Provides tools for determining estimability of linear functions  of regression coefficients, and 'epredict' methods that handle  non-estimable cases correctly. Estimability theory is discussed in many linear-models textbooks including Chapter 3 of Monahan, JF (2008),  "A Primer on Linear Models", Chapman and Hall (ISBN 978-1-4200-6201-4).
# LazyData: yes
# ByteCompile: yes
# License: GPL (>= 3)
# NeedsCompilation: no
# Packaged: 2018-02-11 18:23:39 UTC; rlenth
# Author: Russell Lenth [aut, cre, cph]
# Maintainer: Russell Lenth <russell-lenth@uiowa.edu>
# Repository: CRAN
# Date/Publication: 2018-02-11 20:58:37 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
