travis:
  secure:
    BINSTAR_TOKEN: aQwqKTm3bzPdWBoDmjt1demUy8gMXVg1tB45y0uqXZGmNzm+6BtBStfCAVGf7G17tCd1Tl6/zbXX/aMjiYocSNxctK00Nwn/NluoK4zrROQiCkvc9nf/eAzLZH9uxPR1A6c+ayl5uQE22vW0ZSthzn0/DMBP5DRJCiwaZCbEclyTenJxZ+cQSsAQCZYj7ZdBddCFn8nbWKwiBahAFNv2fSfiqu+YmzzXTj4TlPJEOb7kKVr34toN5Mc58qRUlAdp8FxZqbWFv0QPZWqs9I/uwSFHuZtedn287drI4OLzPEjMXEaI/IkKMqS9yuciP51q8T92bouC/bk30zngskJGVRekfnCtZsB/2lMGFiKYx6Nd1NIlRqmtOMcXn5CfkppR/xMxkO61ZC6/LFs0UQZIyjxUJfSTcJVuFdg9/hp6FKDC+KF/iQ1bCQWxtgbRH3ll0TOAZrHGCo4STIIsl06zu7/Xs0pIltuGRoZuGJ9hfs7tQM8Jv8xUkyTYy6mjWV09REktifRz1Ank9hd6GsELTmmrJjLrqETejp0R2PwyXCZ93gy3BVO7GTDoeif4K1t7nBOEXSMQVZ/Agk1n/SD1YCc625ObgW45yZh5V87TYHHBK/NOJTmo05NVpZmrmTtN3BigLYVFvR49DLs8WTwt6SvcAQlTBTz4h2TH0kVkT6M=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
